# TensorFlow Basics

In [1]:
import tensorflow as tf

## Tensors

In [2]:
node1 = tf.constant([[77, 66], [1, 2]], dtype=tf.float64)
print(node1)

node2 = tf.ones([3,3,3], dtype=tf.int64)
print(node2)

node3 = tf.Variable(tf.random_uniform(shape=(10,10), minval=0, maxval=1))
print(node3)

Tensor("Const:0", shape=(2, 2), dtype=float64)
Tensor("ones:0", shape=(3, 3, 3), dtype=int64)
<tf.Variable 'Variable:0' shape=(10, 10) dtype=float32_ref>


## Workflow

2 phases:
- define the computational graph
- run the graph

### Define the graph

Values have not yet been evaluated:

In [3]:
# definition part
node1 = tf.constant(3.0, dtype=tf.float64)
node2 = tf.constant(4.0, dtype=tf.float64) 
node3 = tf.add(node1, node2)

print(node1)
print(node3)

Tensor("Const_1:0", shape=(), dtype=float64)
Tensor("Add:0", shape=(), dtype=float64)


In [4]:
# we don't have a session yet, so this will not work
# node1.eval()

### Run the graph in a session

Values are now available:

In [5]:
sess = tf.Session()
print(sess.run(node3))

7.0


In [6]:
# we can also directly evaluate nodes now
node3.eval(session=sess)

7.0

## Placeholders and variables

Placeholders are placeholders for external data that will be fed at runtime:

In [7]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.add(a, b)

In [8]:
a, b, c

(<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>,
 <tf.Tensor 'Placeholder_1:0' shape=<unknown> dtype=float32>,
 <tf.Tensor 'Add_1:0' shape=<unknown> dtype=float32>)

In [9]:
# we can feed different shapes
print(sess.run(c, {a: 3, b:4.5}))
print(sess.run(c, {a: [1,3], b: [2, 4]}))

7.5
[ 3.  7.]


Variables are used when values are supposed to change, such as with weights trained by backpropagation.
They are created with an initial value, but the initial value is only assigned when the variable is initialized:

In [10]:
# variables for weights
W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)

# placeholder for input data
x = tf.placeholder(tf.float32)

# a linear model
linear_model = tf.multiply(W, x) + b
# same as tf.multiply - this is element-wise multiplication
# linear_model = W * x + b

In [11]:
W

<tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>

In [12]:
linear_model

<tf.Tensor 'add:0' shape=<unknown> dtype=float32>

In [13]:
# initial variable for weight is not yet initialized
# FailedPreconditionError: Attempting to use uninitialized value
# sess.run(W)

In [14]:
init = tf.global_variables_initializer()
sess.run(init)

In [15]:
sess.run(W)

array([ 0.30000001], dtype=float32)

In [16]:
sess.run(linear_model, {x:[1,2,3,4]})

array([ 0.        ,  0.30000001,  0.60000002,  0.90000004], dtype=float32)

## Broadcasting (reminder)

In [17]:
a = tf.constant([1,2,3], dtype=tf.float32)
b = tf.ones(1)
a,b


(<tf.Tensor 'Const_3:0' shape=(3,) dtype=float32>,
 <tf.Tensor 'ones_1:0' shape=(1,) dtype=float32>)

In [18]:
a + b

<tf.Tensor 'add_1:0' shape=(3,) dtype=float32>

In [19]:
sess.run(a + b)

array([ 2.,  3.,  4.], dtype=float32)