In [10]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

import numpy as np

In [2]:
# load MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [3]:
# input image dimensions
img_rows, img_cols = 28, 28

# reshape into correct order, adding a 4th dimension
if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

In [4]:
# convert to float and normalize
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255


In [5]:
# convert class vectors to binary class matrices
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
y_train.shape, y_test.shape

((60000, 10), (10000, 10))

In [6]:
batch_size = 128
epochs = 1

In [7]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [8]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 178s - loss: 0.3310 - acc: 0.8997 - val_loss: 0.0806 - val_acc: 0.9738


In [11]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.0806416507801
Test accuracy: 0.9738


In [17]:
np.argmax(y_test[:10], axis = 1)

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9])

In [19]:
model.predict_classes(x_test[:10])

10/10 [==============================] - 0s


array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9])

In [20]:
model.predict_proba(x_test[:10])

10/10 [==============================] - 0s


array([[  1.82655143e-07,   8.76623858e-08,   6.20563640e-07,
          4.91511264e-06,   2.21933205e-09,   8.03601741e-10,
          1.31343425e-09,   9.99992490e-01,   4.03553777e-08,
          1.64878713e-06],
       [  5.28962046e-05,   2.58717249e-04,   9.99660969e-01,
          1.05064164e-05,   2.57189559e-08,   3.06540677e-08,
          1.10458632e-05,   1.75341199e-08,   5.71175451e-06,
          1.52805875e-08],
       [  4.73174259e-06,   9.99571025e-01,   6.44461252e-05,
          2.82075325e-05,   4.97250730e-05,   4.38452207e-06,
          4.01517464e-05,   1.29241875e-04,   9.87783278e-05,
          9.29786620e-06],
       [  9.99768078e-01,   1.58495743e-06,   4.96191860e-05,
          9.67237384e-07,   4.73570935e-06,   1.07738151e-05,
          1.10964465e-04,   2.18688565e-05,   7.68482096e-06,
          2.38097018e-05],
       [  5.46953270e-05,   2.29271318e-05,   4.63992910e-06,
          1.22638255e-06,   9.98176217e-01,   7.47641025e-06,
          9.24991473e-05