# Regression task: diabetes

We use scikit-learn to load and preprocess the diabetes data.

In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [2]:
diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target
X.shape, y.shape

((442, 10), (442,))

X Columns

age

sex

bmi

map

tc

ldl

hdl

tch

ltg

glu

In [3]:
X[:10]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087],
       [-0.09269548, -0.04464164, -0.04069594, -0.01944209, -0.06899065,
        -0.07928784,  0.04127682, -0.0763945 , -0.04118039, -0.09634616],
       [-0.04547248,  0.05068012, -0.04716281, -0.01599922, -0.04009564,
        -0.02480001,  0.00077881, -0.03949338

In [4]:
y[:10]

array([ 151.,   75.,  141.,  206.,  135.,   97.,  138.,   63.,  110.,  310.])

In [5]:
# Important: get the target into correct shape for Keras
y = y.reshape(-1,1)
y.shape

(442, 1)

In [6]:
y[:5,:]

array([[ 151.],
       [  75.],
       [ 141.],
       [ 206.],
       [ 135.]])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
# define some hyperparameters

In [10]:
# define the model      

In [11]:
# compile the model

In [9]:
# fit model

In [10]:
# evaluate model

In [11]:
# make some predictions