In [12]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras import backend as K
from keras.optimizers import RMSprop

In [3]:
# load MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [4]:
# flatten
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

In [5]:
# convert to float and normalize
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [7]:
# convert class vectors to binary class matrices
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
y_train.shape, y_test.shape

((60000, 10), (10000, 10))

In [14]:
batch_size = 128
epochs = 1

In [8]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))
model.summary()

In [13]:
model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])


In [15]:
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 11s - loss: 0.2459 - acc: 0.9241 - val_loss: 0.1163 - val_acc: 0.9638


In [16]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.11634876755
Test accuracy: 0.9638


In [17]:
y_test[:10]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [18]:
model.predict_classes(x_test[:10])

10/10 [==============================] - 0s


array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9])

In [20]:
model.predict_proba(x_test[:10])

10/10 [==============================] - 0s


array([[  4.92642982e-07,   1.13448557e-07,   4.18089156e-04,
          1.46456965e-04,   5.21103383e-09,   2.81039570e-06,
          5.18388887e-10,   9.99427319e-01,   1.78845639e-07,
          4.55332111e-06],
       [  8.31254923e-08,   1.00901698e-05,   9.99928713e-01,
          5.90806922e-05,   1.87170543e-10,   3.64143574e-07,
          1.42036663e-06,   8.50381365e-09,   1.82859097e-07,
          1.35728789e-10],
       [  7.54514019e-07,   9.99182880e-01,   4.18427837e-04,
          1.36088620e-05,   5.72452045e-05,   1.99742226e-05,
          6.40581711e-05,   2.11474151e-04,   2.59760054e-05,
          5.48792150e-06],
       [  9.99918699e-01,   2.52816204e-08,   1.64991216e-05,
          6.11468181e-07,   8.99841268e-07,   3.44866453e-06,
          5.35418985e-05,   9.47476053e-07,   4.99072215e-08,
          5.16115097e-06],
       [  1.22086669e-04,   1.13494355e-06,   1.58318871e-04,
          6.40045300e-06,   9.93724525e-01,   6.78138313e-05,
          8.64261528e-04